{
 "title": "Lambda Function",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "the-spanish-decaffeination-etl-lambda"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "the-spanish-decaffeination-etl-lambda"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "the-spanish-decaffeination-etl-lambda"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}